# Generated by Django 5.2.2 on 2025-06-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(),
        ),
    ]
